### ISSUE TITLE
use AHK Expression in JavaScript

### ISSUE THREAD

**Issue by saravananraj21** [Aurelain/Exo#6]
Hi,

I have to get the current logged in windows user.I found that this(A_UserName) expression returns the user name.

Can I use this expression in JavaScript?If so please provide a sample code.

Will this run in all browsers ?

Thanks,
Saravanan S

**Comment by Aurelain** [comment]
If your Javascript runs in a browser, you cannot do that.
It would be a major security risk if you could.

Exo is used only for running Javascript in a local app (exe).
